project_id = "yskajilatxzwtnunxxvs"

[functions.create-connect-account]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false

[functions.create-event-checkout]
verify_jwt = false

[functions.generate-event-description]
verify_jwt = false

[functions.send-ticket-confirmation]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-event-reminders]
verify_jwt = false
