project_id = "qbfgmttcngogxpcwuhzo"

[functions.create-connect-account]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false

[functions.create-event-checkout]
verify_jwt = false

[functions.generate-event-description]
verify_jwt = false

[functions.send-ticket-confirmation]
verify_jwt = false